# Generated by Django 4.0.6 on 2022-07-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=300)),
                ('sku', models.IntegerField(max_length=50)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField(max_length=10)),
                ('categoria', models.CharField(max_length=50)),
                ('sub_categoria', models.CharField(max_length=90)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=100)),
            ],
        ),
    ]
