# Generated by Django 4.0.6 on 2022-07-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.IntegerField(),
        ),
    ]
