# Generated by Django 4.0.6 on 2022-07-08 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_produto_estoque_alter_produto_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Product',
        ),
    ]
